### ISSUE TITLE
possible bug in distances.py

### ISSUE THREAD

**Issue by louil95** [lucastepper/EwaldSummation#2]
Hey when i do the input:

b=np.array([[0,0,0],[1,1,1],[2,2,2]])
print(get_distances(b,1))

i get:
[[0.         0.         0.         0.        ]
 [3.46410162 2.         2.         2.        ]]

is there a bug or is my input false?

**Comment by louil95** [comment]
So after im read the code, i realized the program gives you all coordinates (except particle i) and the distance to the zero vector.

should it be that way?

**Comment by louil95** [comment]
I updatet the file, with the line x = x - particle the new one is in the coulomb branch

**Comment by lucastepper** [comment]
New version in distance should fix the issue
